// wasm_bind.cpp -- Emscripten embind bindings for samp_mdb
// AUTO-GENERATED by bin/wasm-gen samp_mdb
// Do not edit manually
#include "include/algo.h"
#include "include/samp_mdb.h"
#include <emscripten/bind.h>
#include <iostream>

using namespace emscripten;

// Global database instances
algo_lib::FDb algo_lib::_db;
samp_mdb::FDb samp_mdb::_db;

// Stubs for OS functions not available in WASM
void algo::FatalErrorExit(const char *msg) {
    std::cerr << "FATAL: " << msg << std::endl;
    abort();
}

void algo_lib::fildes_Cleanup(algo_lib::FLockfile&) {}
void algo_lib::giveup_time_Step() {}

const tempstr algo::FileToString(const algo::strptr& fname, algo::FileFlags flags) {
    (void)fname; (void)flags;
    return tempstr();
}

bool algo::WriteFile(algo::Fildes fd, u8* buf, int n) {
    (void)fd; (void)buf; (void)n;
    return false;
}

// Helper: convert algo::strptr to std::string for JS
static std::string to_str(algo::strptr s) {
    return std::string(s.elems, s.n_elems);
}

// --- Init ---
static void WasmInit() {
    algo_lib::FDb_Init();
    samp_mdb::FDb_Init();
    samp_mdb::user_Reserve(64);
    samp_mdb::project_Reserve(64);
    samp_mdb::task_Reserve(64);
    samp_mdb::quote_Reserve(64);
}

// --- Insert from ssim string ---
static bool WasmInsertSsim(const std::string& ssim_line) {
    algo::strptr str((char*)ssim_line.c_str(), ssim_line.size());
    algo::strptr type_tag = algo::GetTypeTag(str);

    if (type_tag == "samp_mdb.User") {
        samp_mdb::User* row = samp_mdb::user_AllocMaybe();
        if (!row) return false;
        if (!samp_mdb::User_ReadStrptrMaybe(*row, str)) {
            samp_mdb::user_Delete(*row);
            return false;
        }
        if (!samp_mdb::user_XrefMaybe(*row)) {
            samp_mdb::user_Delete(*row);
            return false;
        }
        return true;
    }
    if (type_tag == "samp_mdb.Project") {
        samp_mdb::Project* row = samp_mdb::project_AllocMaybe();
        if (!row) return false;
        if (!samp_mdb::Project_ReadStrptrMaybe(*row, str)) {
            samp_mdb::project_Delete(*row);
            return false;
        }
        if (!samp_mdb::project_XrefMaybe(*row)) {
            samp_mdb::project_Delete(*row);
            return false;
        }
        return true;
    }
    if (type_tag == "samp_mdb.Task") {
        samp_mdb::Task* row = samp_mdb::task_AllocMaybe();
        if (!row) return false;
        if (!samp_mdb::Task_ReadStrptrMaybe(*row, str)) {
            samp_mdb::task_Delete(*row);
            return false;
        }
        if (!samp_mdb::task_XrefMaybe(*row)) {
            samp_mdb::task_Delete(*row);
            return false;
        }
        return true;
    }
    if (type_tag == "samp_mdb.Quote") {
        samp_mdb::Quote* row = samp_mdb::quote_AllocMaybe();
        if (!row) return false;
        if (!samp_mdb::Quote_ReadStrptrMaybe(*row, str)) {
            samp_mdb::quote_Delete(*row);
            return false;
        }
        if (!samp_mdb::quote_XrefMaybe(*row)) {
            samp_mdb::quote_Delete(*row);
            return false;
        }
        return true;
    }
    return false;
}

// --- Serialize to ssim ---
static std::string WasmToSsim(const std::string& type, const std::string& key) {
    algo::strptr k((char*)key.c_str(), key.size());
    algo::cstring out;
    if (type == "user") {
        samp_mdb::User* row = samp_mdb::ind_user_Find(k);
        if (row) samp_mdb::User_Print(*row, out);
    } else if (type == "project") {
        samp_mdb::Project* row = samp_mdb::ind_project_Find(k);
        if (row) samp_mdb::Project_Print(*row, out);
    } else if (type == "task") {
        samp_mdb::Task* row = samp_mdb::ind_task_Find(k);
        if (row) samp_mdb::Task_Print(*row, out);
    }
    return to_str(out);
}

// --- User list via zd_user ---
static val UserList() {
    val arr = val::array();
    int i = 0;
    for (samp_mdb::User* row = samp_mdb::zd_user_First(); row; row = samp_mdb::zd_user_Next(*row)) {
        val obj = val::object();
        obj.set("user", to_str(row->user));
        obj.set("email", to_str(row->email));
        obj.set("role", to_str(row->role));
        arr.set(i++, obj);
    }
    return arr;
}

static int UserCount() {
    return samp_mdb::zd_user_N();
}

// --- Project list via zd_project ---
static val ProjectList() {
    val arr = val::array();
    int i = 0;
    for (samp_mdb::Project* row = samp_mdb::zd_project_First(); row; row = samp_mdb::zd_project_Next(*row)) {
        val obj = val::object();
        obj.set("project", to_str(row->project));
        obj.set("description", to_str(row->description));
        obj.set("status", to_str(row->status));
        arr.set(i++, obj);
    }
    return arr;
}

static int ProjectCount() {
    return samp_mdb::zd_project_N();
}

// --- Task list via zd_task ---
static val TaskList() {
    val arr = val::array();
    int i = 0;
    for (samp_mdb::Task* row = samp_mdb::zd_task_First(); row; row = samp_mdb::zd_task_Next(*row)) {
        val obj = val::object();
        obj.set("task", to_str(row->task));
        obj.set("title", to_str(row->title));
        obj.set("priority", (int)row->priority);
        obj.set("status", to_str(row->status));
        obj.set("p_project", to_str(row->p_project));
        obj.set("p_user", to_str(row->p_user));
        arr.set(i++, obj);
    }
    return arr;
}

static int TaskCount() {
    return samp_mdb::zd_task_N();
}

// --- Task list via zd_task_priority ---
static val TaskPriorityList() {
    val arr = val::array();
    int i = 0;
    for (samp_mdb::Task* row = samp_mdb::zd_task_priority_First(); row; row = samp_mdb::zd_task_priority_Next(*row)) {
        val obj = val::object();
        obj.set("task", to_str(row->task));
        obj.set("title", to_str(row->title));
        obj.set("priority", (int)row->priority);
        obj.set("status", to_str(row->status));
        obj.set("p_project", to_str(row->p_project));
        obj.set("p_user", to_str(row->p_user));
        arr.set(i++, obj);
    }
    return arr;
}

static int TaskPriorityCount() {
    return samp_mdb::zd_task_priority_N();
}

// --- Quote list via zd_quote ---
static val QuoteList() {
    val arr = val::array();
    int i = 0;
    for (samp_mdb::Quote* row = samp_mdb::zd_quote_First(); row; row = samp_mdb::zd_quote_Next(*row)) {
        val obj = val::object();
        obj.set("quote", to_str(row->quote));
        obj.set("symbol", to_str(row->symbol));
        obj.set("price", row->price);
        obj.set("ts", (double)row->ts);
        arr.set(i++, obj);
    }
    return arr;
}

static int QuoteCount() {
    return samp_mdb::zd_quote_N();
}

// --- User find via ind_user ---
static val UserFind(const std::string& key) {
    samp_mdb::User* row = samp_mdb::ind_user_Find(algo::strptr((char*)key.c_str(), key.size()));
    if (!row) return val::null();
    val obj = val::object();
    obj.set("user", to_str(row->user));
    obj.set("email", to_str(row->email));
    obj.set("role", to_str(row->role));
    return obj;
}

// --- Project find via ind_project ---
static val ProjectFind(const std::string& key) {
    samp_mdb::Project* row = samp_mdb::ind_project_Find(algo::strptr((char*)key.c_str(), key.size()));
    if (!row) return val::null();
    val obj = val::object();
    obj.set("project", to_str(row->project));
    obj.set("description", to_str(row->description));
    obj.set("status", to_str(row->status));
    return obj;
}

// --- Task find via ind_task ---
static val TaskFind(const std::string& key) {
    samp_mdb::Task* row = samp_mdb::ind_task_Find(algo::strptr((char*)key.c_str(), key.size()));
    if (!row) return val::null();
    val obj = val::object();
    obj.set("task", to_str(row->task));
    obj.set("title", to_str(row->title));
    obj.set("priority", (int)row->priority);
    obj.set("status", to_str(row->status));
    obj.set("p_project", to_str(row->p_project));
    obj.set("p_user", to_str(row->p_user));
    return obj;
}

EMSCRIPTEN_BINDINGS(samp_mdb_wasm) {
    function("init", &WasmInit);
    function("insertSsim", &WasmInsertSsim);
    function("toSsim", &WasmToSsim);
    function("userList", &UserList);
    function("userCount", &UserCount);
    function("projectList", &ProjectList);
    function("projectCount", &ProjectCount);
    function("taskList", &TaskList);
    function("taskCount", &TaskCount);
    function("task_priorityList", &TaskPriorityList);
    function("task_priorityCount", &TaskPriorityCount);
    function("quoteList", &QuoteList);
    function("quoteCount", &QuoteCount);
    function("userFind", &UserFind);
    function("projectFind", &ProjectFind);
    function("taskFind", &TaskFind);
}
